# Generated by Django 3.1.7 on 2021-03-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('profilePicture', models.CharField(max_length=15)),
                ('dateOfBirth', models.DateField()),
                ('favoriteFood', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
