# Generated by Django 3.1.7 on 2021-03-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Food form'},
        ),
        migrations.AlterField(
            model_name='food',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='favoriteFood',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='profilePicture',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
